fix: KeyError in module auxiliary_functions.py
File "C:\Users\Daniele.Placido\3D Objects\OPENSC2\source_code\utility_functions\auxiliary_functions.py", line 131, in load_auxiliary_files sheet = wb[sheetname]
File "C:\Users\Daniele.Placido\3D Objects\OPENSC2\source_code\opensc2\lib\site-packages\openpyxl\workbook\workbook.py", line 273, in __getitem__ raise KeyError("Worksheet {0} does not exist.".format(key))
KeyError: 'Worksheet Z_JACKET_1 does not exist.'