fix!: ValueError in __build_heat_source_gauss_pt
ValueError: operands could not be broadcast together with shapes (100,2) (114,2)

This fix is performed removing all methods, functions, variables and
attributes that are related to the array JHTFLX. In the original
architecture of the software, this array was associated to the Joule power,
but while developing the electric module, different variables were introduced
to deal with this quantity an array JHTFLX was only filled with zeros and never
used.

Modified methods:
    * __initialize_heat_source_nodal_pt_th
    * __build_heat_source_nodal_pt
    * __build_heat_source_gauss_pt

Class: SolidComponent, Conductor
modified:   conductor.py
modified:   solid_component.py

BREAKING CHANGES

    Removed method jhtflx0_new from class SolidComponent.