fix: ValueError in method get_joule_power_along
ValueError: operands could not be broadcast together with shapes (100,) (114,)

This bug is reated to the wrong location of the call to method
set_power_array_to_zeros of class SolidComponent. It was called in method
__build_heat_source_gauss_pt of class Conductor (before call to step), but it
is more usefull to call it afther any update of the mesh, outside after the
call to function adaptive_mesh.

Modified method __build_heat_source_gauss_pt in class Conductor and method
conductor_solution in class Simulation.

Class: Conductor, Simulation
modified:   conductor.py
modified:   simulation.py