fix: IndexError in function coarse_mesh
IndexError: list index out of range.

The error is due to the wrong selection of the starting value for key
N_nod_new in dictionary grid_features. Value 1 was selected but Python
starts counting from 0.

modified:   utility_functions/adaptive_mesh_functions.py