fix: AttributeError in function step
AttributeError: 'Interface' object has no attribute 'comp1'.
Similar error would be raised for comp2, so it is corrected in this commit.

Corrected functions:
    * build_smat_env_solid_interface
    * build_svec_env_jacket_interface

modified:   utility_functions/step_matrix_construction.py