fix: ValueError
ValueError: No outputs were able to be calculated

Due to a missing check of the lower bound value of the magnetic field in function critical_current_density_mgb2.

modified:   properties_of_materials/magnesium_diboride.py