fix: TypeError in function build_smat_env_solid_interface
TypeError: 'NoneType' object is not subscriptable (due to a missing returun statement in function build_smat_solid_interface).

Function modified build_smat_solid_interface.
modified:   utility_functions/step_matrix_construction.py