fix: TypeError in function update_mesh
TypeError: type numpy.ndarray doesn't define __round__ method

modified:   utility_functions/adaptive_mesh_functions.py