fix: TypeError in method __check_cross_section of class StrandMixedComponent
TypeError: _isclose_dispatcher() missing 1 required positional argument: 'b'.