fix: TypeError in function step
TypeError: build_kmat_fluid() missing 1 required positional argument: 'elem_idx'.

modified:   utility_functions/transient_solution_functions.py