fix: KeyError in method conductor_instance
KeyError: 'Worksheet CONDUCTOR_operation does not exist.'

modified:   ../TDD_examples/CASE_2_ENEA_HTS_CICC/conductor_definition.xlsx