fix: IndexError in update_value
IndexError: index 113 is out of bounds for axis 0 with size 100

This bug is due to the not update of array delta_voltage_along_sum on the new
mesh.
To fix it:
    1. method update_delta_voltage_along_on_new_mesh of class StrandComponent
    and JacketComponent returns a tuple collecting arrays delta_voltage_along
    and delta_voltage_along_sum correctly updated on the new mesh
    (re-initialized to 0);
    2. in function adaptive_mesh, where method
    update_delta_voltage_along_on_new_mesh is called changes are implemented to
    keep into account the new output of the method.

Class: JacketComponent, StrandComponent
modified:   jacket_component.py
modified:   strand_component.py
modified:   utility_functions/adaptive_mesh_functions.py