fix: NameError in method __init__
NameError: ERROR in method __init__ of class Conductor: kind object STR_SC does not exist.
Please check cell A1 in sheet <Worksheet "STACK"> of file conductor_1_input.xlsx.

modified:   ../TDD_examples/CASE_3_HTS_HVDC/conductor_1_input.xlsx
modified:   ../TDD_examples/CASE_3_HTS_HVDC/conductor_1_operation.xlsx