fix: TypeError in function update_values
TypeError: 'int' object is not subscriptable
Error due to int return in function current_sharing_temperature_mgb2.

modified:   properties_of_materials/magnesium_diboride.py