fix: TypeError in function step
TypeError: eval_sub_array_norm() missing 1 required positional argument: 'eq_idx'.

modified:   utility_functions/transient_solution_functions.py