fix: KeyError in method eval_transp_coeff
KeyError: 'total_thermal_conductivity'.

This error is mainly due to the fact that variable conductive heat transfer coefficients are introduced as a new feature of the code.
This fix is quite complicated since it involves several changes in two modules, namely conductor.py and simulation.py.
Below the main changes to make the fix.
Module conductor.py, class Conductor:
    * call method self.operating_conditions_em before method self.operating_conditions_th_initialization in method self.initialization.
    * removed loop on SolidComponents to evaluate thermophisical properties, since they are evaluated when method self.operating_conditions_em is called in both nodal and Gauss points
    * evaluate SolidComponents thermophisical properties in method self.operating_conditions_em
    * new private method self.__eval_temperature_solids_gauss_point
    * call method self.__eval_temperature_solids_gauss_point at the beginning of method self.__eval_gauss_point_em
    * remove evaluation of temperature of SolidComponents in Gauss point from method self.__eval_gauss_point_th since it is evaluated in method self.__eval_gauss_point_em; doctring is evaluated accordingly

Module simulation.py, class Simulation:
    * call method conductor.operating_conditions_th after the end of the electric loop in method self.conductor_solution.

Class: Conductor, Simulation.

modified:   conductor.py
modified:   simulation.py