fix: TypeError in class Conductor
File "C:\Users\Daniele.Placido\3D Objects\OPENSC2\source_code\conductor.py", line 3537, in electric_method electric_transient_solution()
TypeError: electric_transient_solution() missing 1 required positional argument: 'conductor'