fix: ValueError in method __check_variable_contact_perimeter_consistency
Changes in method __check_variable_contact_perimeter_consistency in order to get the following error if user does not correctly writes the auxiliary file for variable contact perimeter.

ValueError: Found missing interfaces with a variable contact perimeter. Please, in auxiliary input file variable_contact_perimeter.xlsx, add the columns reported in the following table (columns header are sheet names, values are missing columns in the sheet)

Class: Conductor.

modified:   conductor.py