fix: ValueError in store_interp_spatial_distributions
ValueError: fp and xp are not of the same length.

The bug is due to the fact that a shallow copy of attribute dictionary
self.heat_rad_jk of class Conductor was saved in attribute dictionary
self.store_sd_gauss["heat_rad_jk"]["t_save_left"]. When attribute
self.heat_rad_jk is updated in method self.compute_radiative_heat_exhange_jk,
the also value stored in attribute
self.store_sd_gauss["heat_rad_jk"]["t_save_left"] is updated but this is an
unwanted beavior.
To fix this in method __store_sd_conductor the copy method is used.

Class: Conductor
modified:   conductor.py