fix: KeyError in store_interp_spatial_distributions
KeyError: 'CHAN_1_STR_MIX_1'

This error is due to the missing initialization of keyword t_save_left of
attribute dictionary self.store_sd_node of class Conductor.
This is done calling method self.store_spatial_distributions_t0 with
t_save_key = t_save_left in method self.conductor_solution of class
Simulation.

This error occurs when user wants to save spatial distributions at the first
time step after the initialization.

Class: Simulation
modified:   simulation.py