fix: TypeError in method strand_thermal_conductivity
TypeError: thermal_conductivity_mgb2() missing 1 required positional argument: 'b'.

modified:   strand_mixed_component.py