fix: ValueError in method interp_solution_on_new_mesh
ValueError: could not broadcast input array from shape (115,) into shape (101,).

This error is due to the fact that Python starts counting from 0, so node
counter N_node_new in attribute dictionary grid_features of class Component
must start from. However, without any further correction, there will be a
mismatch between the counter and the lenght of the updaded mesh zcoord_new.
To fix this issue, it is necessary to add 1 to the final value of N_node_new
before exiting function update_mesh.

This explains why the fix is carried out in function update_mesh rather than in
method interp_solution_on_new_mesh of class Conductor.

modified:   utility_functions/adaptive_mesh_functions.py