fix: TypeError in function step
TypeError: ndarray_initialization() missing 1 required positional argument: 'collector_keys'.

modified:   utility_functions/transient_solution_functions.py