fix: TypeError in method __build_heat_source_gauss_pt
TypeError: set_power_array_to_zeros() missing 1 required positional argument: 'conductor'.

Class: Conductor
modified:   conductor.py