fix: TypeError in method operating_conditions_th
TypeError: __update_grid_features() missing 1 required positional argument:
'grid_features'.

Class: Conductor
modified:   conductor.py